# @package _global_

method:
  _target_: robobase.method.dit.DiT
  is_rl: false
  lr: 1e-4
  num_train_steps: ${num_pretrain_steps}
  adaptive_lr: false
  diffusion_timesteps: 6  # Temp: 6 for dev. Should be 100 for real experiments.
  eval_diffusion_timesteps: 2  # Temp: 2 for dev. Should be 10 for real experiments.

  encoder_model:
    _target_: robobase.models.tokenizing_encoder.TokenizingEncoder
    _partial_: true
    d_model: 128  # Temp: 128 for dev. Should be 512 for real experiments.
    frame_stack: ${frame_stack}

  actor_model:
    _target_: robobase.models.dit_models.DiTPolicyModel
    _partial_: true
    d_model: ${method.encoder_model.d_model}
    num_decoder_layers: 4
    num_heads: 8

  self_attention_encoder_model:
    _target_: robobase.models.dit_models.SelfAttentionEncoder
    _partial_: true
    d_model: ${method.encoder_model.d_model}
    num_layers: 4
    num_heads: 8

  proprio_projector:
    _target_: robobase.models.dit_models.ProprioProjector
    _partial_: true
    input_dim: 66
    hidden_dim: 1024
    output_dim: ${method.encoder_model.d_model}